import {
  meta,
  shopify,
  starbucks,
  tesla,
  centralAcademy,
  mps,
  coding,
  programming,
  webDev,
  atom,
  hashtag,
  cpp,
  mit,
  crosscountryLogo,
  NEULogo,
} from "../assets/images";
import {
  car,
  contact,
  css,
  estate,
  express,
  git,
  github,
  html,
  javascript,
  linkedin,
  mongodb,
  motion,
  mui,
  nextjs,
  nodejs,
  pricewise,
  react,
  redux,
  sass,
  snapgram,
  summiz,
  tailwindcss,
  threads,
  typescript,
  unity,
  cSharp,
  c,
  cPlus,
  java,
  threejs,
  tent,
  todo,
  cube,
  vw,
  tshirt,
  urdrobe,
  quirepad,
  reactNative,
  swift,
  firebase,
} from "../assets/icons";

export const skills = [
  {
    imageUrl: css,
    name: "CSS",
    type: "Frontend",
    efficiency: 10,
  },
  {
    imageUrl: express,
    name: "Express",
    type: "Backend",
    efficiency: 9,
  },
  {
    imageUrl: git,
    name: "Git",
    type: "Version Control",
    efficiency: 9,
  },
  {
    imageUrl: github,
    name: "GitHub",
    type: "Version Control",
    efficiency: 10,
  },
  {
    imageUrl: html,
    name: "HTML",
    type: "Frontend",
    efficiency: 10,
  },
  {
    imageUrl: javascript,
    name: "JavaScript",
    type: "Frontend",
    efficiency: 9,
  },
  {
    imageUrl: mongodb,
    name: "MongoDB",
    type: "Database",
    efficiency: 10,
  },
  // {
  //     imageUrl: motion,
  //     name: "Motion",
  //     type: "Animation",
  // },
  {
    imageUrl: mui,
    name: "Material-UI",
    type: "Frontend",
    efficiency: 10,
  },
  {
    imageUrl: nextjs,
    name: "Next.js",
    type: "Frontend",
    efficiency: 7,
  },
  {
    imageUrl: nodejs,
    name: "Node.js",
    type: "Backend",
    efficiency: 10,
  },
  {
    imageUrl: react,
    name: "React",
    type: "Frontend",
    efficiency: 10,
  },
  // {
  //     imageUrl: redux,
  //     name: "Redux",
  //     type: "State Management",
  // },
  // {
  //     imageUrl: sass,
  //     name: "Sass",
  //     type: "Frontend",
  // },
  {
    imageUrl: tailwindcss,
    name: "Tailwind CSS",
    type: "Frontend",
    efficiency: 9,
  },
  {
    imageUrl: typescript,
    name: "TypeScript",
    type: "Frontend",
    efficiency: 8,
  },
  {
    imageUrl: unity,
    name: "Unity",
    type: "GamingEngine",
    efficiency: 5,
  },
  {
    imageUrl: cSharp,
    name: "C#",
    type: "Language",
    efficiency: 5,
  },
  {
    imageUrl: c,
    name: "C",
    type: "Language",
    efficiency: 7,
  },
  {
    imageUrl: cPlus,
    name: "C++",
    type: "Language",
    efficiency: 9,
  },
  {
    imageUrl: java,
    name: "Java",
    type: "Language",
    efficiency: 8,
  },
  {
    imageUrl: threejs,
    name: "Threejs",
    type: "Frontend",
    efficiency: 10,
  },
  {
    imageUrl: reactNative,
    name: "React Native",
    type: "Frontend",
    efficiency: 8,
  },
  {
    imageUrl: swift,
    name: "Swift",
    type: "Language",
    efficiency: 6,
  },
  {
    imageUrl: firebase,
    name: "Firebase",
    type: "Backend",
    efficiency: 10,
  },
];

export const experiences = [
  {
    title: "SSC",
    company_name: "From Central Academy, Prayagraj",
    icon: centralAcademy,
    iconBg: "#accbe1",
    date: "2019",
    points: ["With SSC 88%"],
  },
  {
    title: "HSC",
    company_name: "From Maheshwari Public School, Kota",
    icon: mps,
    iconBg: "#fbc3bc",
    date: "2021",
    points: ["With HSC 75%"],
  },
  {
    title: "Started learning C and C++",
    company_name:
      "combining visual fundamentals and object-oriented programming",
    icon: coding,
    iconBg: "#b7e4c7",
    date: "January 2022",
    points: [],
  },
  {
    title: "Started learning Python and Java",
    company_name:
      " focusing on dynamic scripting and advanced object-oriented programming concepts.",
    icon: programming,
    iconBg: "#a2d2ff",
    date: "August 2022",
    points: [],
  },
  {
    title: "Started Web development course",
    company_name: " From Udemy",
    icon: webDev,
    iconBg: "#8dd5f6",
    date: "April 2023",
    points: [],
  },
  {
    title:
      " Web development course completion and embarking on creating innovative projects...",
    company_name: "Projects include YelpCamp and React Todo List",
    icon: atom,
    iconBg: "#F8ABB9",
    date: "February 2024",
    points: [],
  },
  {
    title: " Started Game development course",
    company_name: "From Udemy and made my first 2D game 'Galaxy Shooter'",
    icon: hashtag,
    iconBg: "#cbafed",
    date: "March 2024",
    points: [],
  },
  {
    title: " Started C++ DSA Course",
    company_name: "From Udemy along with solving Leetcode exercises",
    icon: cpp,
    iconBg: "#6CC5D9",
    date: "May 2024",
    points: [],
  },
  {
    title: "BTech Computer Science",
    company_name: "From MIT WPU",
    icon: mit,
    iconBg: "#e3dcdc",
    date: "2021-2025",
    points: ["Graduated in June 2025 with a CGPA of 7.7/10"],
  },
  {
    title: "Software Intern",
    company_name: "Cross Country Infotech",
    icon: crosscountryLogo,
    iconBg: "#b7e4c7",
    date: "January 2025",
    points: [],
  },
  {
    title: "Software Engineer Trainee",
    company_name: "Cross Country Infotech",
    icon: crosscountryLogo,
    iconBg: "#a2d2ff",
    date: "August 2025 - December 2025",
    points: [],
  },
  {
    title: "MSCS at Northeastern University",
    company_name: "Boston",
    icon: NEULogo,
    iconBg: "#F8ABB9",
    date: "January 2026 - May 2028",
    points: [],
  },
  {
    title: "Built & Deployed UrDrobe",
    company_name: "Available on the App Store",
    icon: urdrobe,
    iconBg: "#accbe1",
    date: "January 2026 - May 2026",
    points: ["Built and deployed an AI-powered virtual wardrobe iOS app"],
  },
  {
    title: "Built & Deployed Quirepad",
    company_name: "Available on the Mac App Store",
    icon: quirepad,
    iconBg: "#6CC5D9",
    date: "July 2026",
    points: ["Built and deployed a Safari extension for macOS and iOS"],
  },
];

export const socialLinks = [
  {
    name: "Contact",
    iconUrl: contact,
    link: "/contact",
  },
  {
    name: "GitHub",
    iconUrl: github,
    link: "https://github.com/YourGitHubUsername",
  },
  {
    name: "LinkedIn",
    iconUrl: linkedin,
    link: "https://www.linkedin.com/in/YourLinkedInUsername",
  },
];

export const projects = [
  {
    iconUrl: urdrobe,
    theme: "btn-back-white",
    name: "Urdrobe",
    description:
      "UrDrobe is an AI-powered virtual wardrobe app that turns your physical closet into an organized digital one. Snap a single photo of an outfit and its AI instantly detects, cuts out, and catalogs every individual piece. It helps you build outfits, plan them on a calendar, and try them on virtually. The app learns your wardrobe to deliver daily outfit suggestions tuned to your weather, tracks how often you wear each item, and even knows what's clean versus in the laundry. Built as a free, ad-free iOS app.",
    link: "https://apple.co/4u1idhw",
  },
  {
    iconUrl: quirepad,
    theme: "btn-back-black",
    name: "Quirepad",
    description:
      "Quirepad is a Safari extension for macOS and iOS that lets you select text across pages and tabs and merge it all into one clipboard paste, grouped by source, with everything stored locally and no accounts or tracking.",
    link: "https://apps.apple.com/us/app/quirepad/id6792422405?mt=12",
    linkLabel: "App Store",
  },
  {
    iconUrl: todo,
    theme: "btn-back-green",
    name: "React ToDO List",
    description:
      " A Todo List made using React, Material UI, and Local Storage!",
    link: "https://react-todolist-p4zi.onrender.com",
  },
  {
    iconUrl: cube,
    theme: "btn-back-blue",
    name: "3D Portfolio Website",
    description:
      "Explore my 3D portfolio, crafted using React and Three.js, where creativity meets cutting-edge technology. This interactive experience showcases my skills in web development and 3D rendering, offering a dynamic and immersive way to navigate through my work and achievements. Dive in to see my projects come to life in a whole new dimension.",
    link: "",
  },
  {
    iconUrl: snapgram,
    theme: "btn-back-pink",
    name: "Galaxy Shooter",
    description:
      "In Galaxy Shooter, you control a spaceship navigating through space. Your objective is to destroy enemy ships and avoid obstacles. Collect power-ups to boost your abilities and survive as long as possible to achieve a high score.",
    link: "https://saurabhsm11.itch.io/galaxy-shooter",
  },
  {
    iconUrl: tshirt,
    theme: "btn-back-yellow",
    name: "ShirtLab",
    description:
      "ShirtLab: An interactive 3D web application that allows users to customize shirts with AI-generated designs, upload custom images, and explore a range of colors and styles, offering a seamless blend of creativity and personalization.",
    link: "https://shirtlab-rnyn.onrender.com",
  },
  // {
  //     iconUrl: estate,
  //     theme: 'btn-back-black',
  //     name: 'Real-Estate Application',
  //     description: 'Developed a web application for real estate listings, facilitating property searches and connecting buyers with sellers.',
  //     link: 'https://github.com/adrianhajdin/projects_realestate',
  // },
  // {
  //     iconUrl: summiz,
  //     theme: 'btn-back-yellow',
  //     name: 'AI Summarizer Application',
  //     description: 'App that leverages AI to automatically generate concise & informative summaries from lengthy text content, or blogs.',
  //     link: 'https://github.com/adrianhajdin/project_ai_summarizer',
  // }
];
